### PR TITLE
(Idea) prompt user to input task name if no argument is provided

### PR DESCRIPTION
**Pull request by jihchi**
Preview:

2017-03-03_15-56-59_upk4i

### CODE REVIEW

**Comment by bahmutov** [comment]
See, I love what you are doing here (especially how thorough), but I don't like this. For me, the beauty of this was very quick tool that either:
- shows all scripts if just `nr`
- shows scripts with prefix if `nr prefix`
- runs a script if it can be uniquely identified by prefix
Adding a inquirer means the user can go through a few scripts? How many scripts does a package.json need to have for this to be useful? Can you give me an example where this would be useful?

**Comment by jihchi** [comment]
Would it be better if I add extra argument in CLI (for example: `nr -i/--interactive`) for this use case?

Because most of the time I can't remember script name in each projects I'm working,
I need to execute `nr` to have a glimpse on screen and search the item through my eyes,
Finally, I can execute `nr {keyword}` to run the script.

So, I want to combine those two steps (`nr` then `nr {keyword}`) into one step, I could just execute `nr --interactive` and 
continue type keyword to select the item.

**Comment by bahmutov** [comment]
so I like the `-i` idea - then people could actually define an alias so that it starts the interactive mode automatically. And it will keep the old way still working (so no breaking change). If you add `-i` I promise to merge it quickly!

**Comment by bahmutov** [comment]
@jihchi I just added you as a collaborator to this project. Semantic release is setup, feel free to improve and commit / merge your code, ok

**Pull request merged**
